name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar versão do .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # Build do projeto
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Rodar testes
      - name: Run tests
        run: dotnet test --configuration Release --no-restore

  docker:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build das imagens Docker
      - name: Build Docker images
        run: |
          docker build -t cleytonsantos/payconnect-payment-webapi:latest -f src/PayConnect.Payment.WebApi/Dockerfile .
          docker build -t cleytonsantos/payconnect-transaction-webapi:latest -f src/PayConnect.Transaction.WebApi/Dockerfile .

      # Push das imagens para o Docker Hub
      - name: Push Docker images
        run: |
          docker push cleytonsantos/payconnect-payment-webapi:latest
          docker push cleytonsantos/payconnect-transaction-webapi:latest
